//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UAS.Core.DAL.Common.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClassificationByRoleView
    {
        public int IdClassification { get; set; }
        public string Classification { get; set; }
        public int IdRole { get; set; }
        public string RoleName { get; set; }
        public string RoleAlias { get; set; }
        public Nullable<bool> IsRequiredDescription { get; set; }
    }
}
