//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UAS.Core.DAL.Common.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Enrollment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Enrollment()
        {
            this.EnrollmentDetails = new HashSet<EnrollmentDetail>();
        }
    
        public int Id { get; set; }
        public int StudentDocumentNumber { get; set; }
        public int IdEnrollmentStatus { get; set; }
        public int IdAcademicPeriod { get; set; }
        public System.DateTime RegisterDate { get; set; }
    
        public virtual AcademicPeriod AcademicPeriod { get; set; }
        public virtual EnrollmentStatu EnrollmentStatu { get; set; }
        public virtual Student Student { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EnrollmentDetail> EnrollmentDetails { get; set; }
    }
}
