//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UAS.Core.DAL.Common.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Enrollment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Enrollment()
        {
            this.EnrollmentDetails = new HashSet<EnrollmentDetail>();
        }
    
        public int Id { get; set; }
        public int StudentDocumentNumber { get; set; }
        public int IdEnrollmentStatus { get; set; }
        public int IdAcademicPeriod { get; set; }
        public System.DateTime RegisterDate { get; set; }
    
        public virtual AcademicPeriod AcademicPeriod { get; set; }
        public virtual EnrollmentStatu EnrollmentStatu { get; set; }
        public virtual Student Student { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EnrollmentDetail> EnrollmentDetails { get; set; }
    }
}
