//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UAS.Core.DAL.Common.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Excuse
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Excuse()
        {
            this.Attachments = new HashSet<Attachment>();
            this.ExcuseDetails = new HashSet<ExcuseDetail>();
        }
    
        public int Id { get; set; }
        public int IdStatus { get; set; }
        public int IdClassification { get; set; }
        public int IdUserOwner { get; set; }
        public string Justification { get; set; }
        public string Observation { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> RegisterDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> LastModificationDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Attachment> Attachments { get; set; }
        public virtual Classification Classification { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExcuseDetail> ExcuseDetails { get; set; }
        public virtual User User { get; set; }
        public virtual Status Status { get; set; }
    }
}
