//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UAS.Core.DAL.Common.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExcuseDetail
    {
        public int Id { get; set; }
        public int IdExcuse { get; set; }
        public int IdStatus { get; set; }
        public int IdUserApprover { get; set; }
        public Nullable<System.DateTime> RegisterDate { get; set; }
    
        public virtual Excuse Excuse { get; set; }
        public virtual User User { get; set; }
        public virtual Status Status { get; set; }
    }
}
