//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UAS.Core.DAL.Common.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Excuse
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Excuse()
        {
            this.Attachments = new HashSet<Attachment>();
            this.ExcuseApprovals = new HashSet<ExcuseApproval>();
        }
    
        public int Id { get; set; }
        public int IdNonAttendance { get; set; }
        public int DocumentNumber { get; set; }
        public int IdStatus { get; set; }
        public int IdClassification { get; set; }
        public string Justification { get; set; }
        public string Observation { get; set; }
        public Nullable<System.DateTime> RegisterDate { get; set; }
        public int IdRole { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Attachment> Attachments { get; set; }
        public virtual Classification Classification { get; set; }
        public virtual NonAttendance NonAttendance { get; set; }
        public virtual Status Status { get; set; }
        public virtual Role Role { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExcuseApproval> ExcuseApprovals { get; set; }
    }
}
