//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UAS.Core.DAL.Common.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExcuseApprovalView
    {
        public int Id { get; set; }
        public int IdExcuse { get; set; }
        public int IdStatusApproval { get; set; }
        public string StatusApproval { get; set; }
        public int Approver { get; set; }
        public int IdRoleApprover { get; set; }
        public int IdNonAttendance { get; set; }
        public int TruantDocumentNumber { get; set; }
        public string TruantFullName { get; set; }
        public int CourseId { get; set; }
        public string CourseName { get; set; }
        public int DayOfTheWeek { get; set; }
        public string NameDayOfTheWeek { get; set; }
        public int SpaceId { get; set; }
        public string SpaceName { get; set; }
        public string SpaceType { get; set; }
        public System.TimeSpan StartTime { get; set; }
        public System.TimeSpan EndTime { get; set; }
        public System.DateTime NonAttendanceDate { get; set; }
        public bool HasExcuse { get; set; }
        public int IdStatusExcuse { get; set; }
        public string StatusExcuse { get; set; }
        public int IdClassificationExcuse { get; set; }
        public string ClassificationExcuse { get; set; }
        public string ExcuseJustification { get; set; }
        public string ExcuseObservation { get; set; }
    }
}
