//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UAS.Core.DAL.Common.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExcuseView
    {
        public int Id { get; set; }
        public int IdNonAttendance { get; set; }
        public int TruantDocumentNumber { get; set; }
        public string TruantFullName { get; set; }
        public string TruantRoleId { get; set; }
        public string TruantRoleAlias { get; set; }
        public int CourseId { get; set; }
        public string CourseName { get; set; }
        public int DayOfTheWeek { get; set; }
        public string NameDayOfTheWeek { get; set; }
        public int SpaceId { get; set; }
        public string SpaceName { get; set; }
        public string SpaceType { get; set; }
        public System.TimeSpan StartTime { get; set; }
        public System.TimeSpan EndTime { get; set; }
        public System.DateTime NonAttendanceDate { get; set; }
        public bool HasExcuse { get; set; }
        public int IdRole { get; set; }
        public int IdStatus { get; set; }
        public string Status { get; set; }
        public bool IsLast { get; set; }
        public int IdClassification { get; set; }
        public string Classification { get; set; }
        public string ExcuseJustification { get; set; }
        public string ExcuseObservation { get; set; }
    }
}
