//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UAS.Core.DAL.Common.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExcuseDetail
    {
        public int Id { get; set; }
        public int IdExcuse { get; set; }
        public int IdStatus { get; set; }
        public int IdUserApprover { get; set; }
        public Nullable<System.DateTime> RegisterDate { get; set; }
    
        public virtual Excuse Excuse { get; set; }
        public virtual User User { get; set; }
        public virtual Status Status { get; set; }
    }
}
