//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UAS.Core.DAL.Common.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PagePermissionByRole
    {
        public int IdPage { get; set; }
        public int IdRole { get; set; }
        public bool IsDefault { get; set; }
        public bool IsVisible { get; set; }
        public bool CanEdit { get; set; }
        public bool CanUpdate { get; set; }
        public bool CanSelect { get; set; }
        public bool CanDelete { get; set; }
    
        public virtual Page Page { get; set; }
        public virtual Role Role { get; set; }
    }
}
