//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UAS.Core.DAL.Common.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ScheduleDetail
    {
        public int Id { get; set; }
        public int IdSchedule { get; set; }
        public int DayOfTheWeek { get; set; }
        public System.TimeSpan StartTime { get; set; }
        public System.TimeSpan EndTime { get; set; }
        public Nullable<System.DateTime> RegisterDate { get; set; }
        public int IdSpace { get; set; }
    
        public virtual Schedule Schedule { get; set; }
        public virtual Space Space { get; set; }
    }
}
