//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UAS.Core.DAL.Common.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ScheduleDetail
    {
        public int Id { get; set; }
        public int IdSchedule { get; set; }
        public int DayOfTheWeek { get; set; }
        public System.TimeSpan StartTime { get; set; }
        public System.TimeSpan EndTime { get; set; }
        public Nullable<System.DateTime> RegisterDate { get; set; }
        public int IdSpace { get; set; }
    
        public virtual Schedule Schedule { get; set; }
        public virtual Space Space { get; set; }
    }
}
