//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UAS.Core.DAL.Common.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentEnrollmentView
    {
        public Nullable<int> StudentDocumentNumber { get; set; }
        public Nullable<int> StudentCode { get; set; }
        public string StudentName { get; set; }
        public string StudentLastName { get; set; }
        public string StudentFullName { get; set; }
        public string StudentEmail { get; set; }
        public Nullable<int> StudentTelephoneNumber { get; set; }
        public string StudentAddress { get; set; }
        public string StudentImageRelativePath { get; set; }
        public Nullable<int> CareerId { get; set; }
        public Nullable<int> CareerCode { get; set; }
        public string CareerName { get; set; }
        public string FringeName { get; set; }
        public Nullable<int> TeacherDocumentNumber { get; set; }
        public Nullable<int> TeacherCode { get; set; }
        public string TeacherName { get; set; }
        public string TeacherLastName { get; set; }
        public string TeacherEmail { get; set; }
        public Nullable<int> TeacherTelephoneNumber { get; set; }
        public string TeacherAddress { get; set; }
        public string TeacherImageRelativePath { get; set; }
        public string TeacherFullName { get; set; }
        public Nullable<int> CourseId { get; set; }
        public string CourseName { get; set; }
        public Nullable<int> CourseCredits { get; set; }
        public Nullable<int> DayOfTheWeek { get; set; }
        public string DayOfTheWeekName { get; set; }
        public Nullable<System.TimeSpan> StartTime { get; set; }
        public Nullable<System.TimeSpan> EndTime { get; set; }
        public Nullable<int> AcademicPeriod { get; set; }
        public Nullable<int> AcademicSemester { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string EnrollmentStatus { get; set; }
    }
}
