//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UAS.Core.DAL.Common.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int Id { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public int IdRole { get; set; }
        public string Name { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public Nullable<int> TelephoneNumber { get; set; }
        public bool IsActive { get; set; }
        public Nullable<System.DateTime> RegisterDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> LastModiticationDate { get; set; }
        public string ModifiedBy { get; set; }
        public int DocumentNumber { get; set; }
        public string ImageRelativePath { get; set; }
    
        public virtual Role Role { get; set; }
    }
}
